In [10]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

In [14]:
weights = [0.1, 0.2, 0]
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred

In [42]:
toes = [8.5, 9.5, 10, 9]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)
#print("{0:0.2f}".format(pred))
#print(pred)

0.9800000000000001


# Predict result by toes, winrate and number of fans (3 inputs, 1 output)

In [41]:
# predict result by toes, winrate and number of fans (3 inputs, 1 output)
import numpy as np
weights = np.array([0.1, 0.2, 0])
def neu_network(input, weights):
    pred = input.dot(weights)
    return pred

toes = np.array([8.5, 9.5, 10, 9])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neu_network(input, weights)
print(pred)

0.9800000000000001


In [33]:
def elementwise_multiplication(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output.append(vec_a[i] * vec_b[i])
    return output

def elementwise_addiction(vec_a, vec_b):
    assert(len(vec_a) == len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output.append(vec_a[i] + vec_b[i])
    return output

def vector_sum(vec_a):
    output = 0
    for item in vec_a:
        output += item
    return output

def vector_average(vec_a):
    output = 0
    assert(len(vec_a) != 0)
    for item in vec_a:
        output += item
    output /= len(vec_a)
    return output

In [37]:
a = [5, 3, 7]
b = [6, 4, 9]
print(elementwise_multiplication(a, b))
print(elementwise_addiction(a, b))
print(vector_sum(a))
print(vector_average(a))
print(vector_sum(elementwise_multiplication(a, b)))

[30, 12, 63]
[11, 7, 16]
15
5.0
105


# Predict injuries, result, bad mood by winrate (1 input, 3 outputs)

In [4]:
def ele_mul(number, vector):
    output = [0,0,0]
    assert(len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

weights = [0.3, 0.2, 0.9]
def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred

wlrec = [0.65, 0.8, 0.8, 0.9]
input = wlrec[0]
pred = neural_network(input, weights)
print(pred)

[0.195, 0.13, 0.5850000000000001]


# Predict injuries, result, bad mood by num of games, winrate and num of fans (3 inputs, 3 outputs)

In [29]:
#        #games #winr #nfans
weights = [[0.1, 0.1, -0.3], # injuries
           [0.1, 0.2, 0.0], #result
           [0.0, 1.3, 0.1]] #bad mood

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0,0,0]
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


# Network with one hidden layer (3 inputs, 3 outputs)

In [33]:
#       #games #winr #nfans
ih_wgt = [[0.1, 0.2, -0.1], #hid[0]
          [-0.1, 0.1, 0.9], #hid[1]
          [0.1, 0.4, 0.1]] #hid[2]
#      #hid[0] #hid[1] #hid[2]
hp_wgt = [[0.1, 0.2, -0.1], #injuries
          [-0.1, 0.1, 0.9], #result
          [0.1, 0.4, 0.1]]  #bad mood
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    print(hid)
    pred = vect_mat_mul(hid, weights[1])
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.8600000000000001, 0.29499999999999993, 1.23]
[0.02200000000000002, 1.0505, 0.327]


## Version with NumPy

In [36]:
import numpy as np
# games winrate nfans
ih_wgt = np.array(
            [[0.1, 0.2, -0.1], #hid[0]
            [-0.1, 0.1, 0.9], #hid[1]
            [0.1, 0.4, 0.1]]).T #hid[2]

#          hid[0] hid[1] hid[2]
hp_wgt = np.array(
            [[0.1, 0.2, -0.1], #injuries
            [-0.1, 0.1, 0.9], #result
            [0.1, 0.4, 0.1]]).T #bad mood
weights = [ih_wgt, hp_wgt]
def neural_network(input, weights):
    hid = input.dot(weights[0])
    print(hid)
    pred = hid.dot(weights[1])
    return pred

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)

[0.86  0.295 1.23 ]
[0.022  1.0505 0.327 ]


# Grokking numpy

In [39]:
import numpy as np

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7]])
d = np.zeros((2, 4))
e = np.random.rand(2, 5)

print(a)
print(b)
print(c)
print(d)
print(e)

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.60243565 0.46053438 0.23028166 0.48471197 0.13873822]
 [0.21486538 0.19272049 0.74660209 0.81920878 0.2536439 ]]


In [42]:
print(a * 0.1)
print(c * 0.2)
print(a * b)
print(a * b * 0.2)
print(a * c)
print(a * e)

[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [44]:
a = np.zeros((1, 4))
b = np.zeros((4, 3))
c = a.dot(b)
print(c.shape)

(1, 3)


In [46]:
from platform import python_version

print(python_version())
import numpy
numpy.version.version

3.8.3


'1.19.5'